// ACTIVIDAD DE TENER 15 ELEMENTOS DE DATAPERSONA CON DIFERENTES VALORES
// 1. MOSTRAR POR PANTALLA EL PROMEDIO DE LAS EDADES
// 2. FILTRADO POR NOMBRE (COINCIDA LETRA O PALABRA)
// 3. (EL USUARIO INGRESARA EL CRITERIO A BUSCAR (LETRA O PALABRA)